In [1]:
import pandas as pd
import requests
import glob
import json
import time
import matplotlib.pyplot as plt
import numpy as np
import pickle

## Load Data from Text Files into Pandas DataFrames

The log files are read in one line at a time, adding each data point to a pandas dataframe.

In [2]:
site_dataframes = {}

for filename in glob.glob('./MinuteLogs/log*'):
    with open(filename, 'r') as logfile:
        sites_response_string = logfile.readline()
        try:
            sites_dict = json.loads(sites_response_string)
        except ValueError as err:
            with open('./Error_Log.txt','w+') as f:
                f.write("JSON Conversion Error in "+filename+" for Sites Response: "+str(err))
            continue
                         
        # Process each signal response
        for signals_response_string in logfile:
            try:
                signals_dict = json.loads(signals_response_string)
            except ValueError as e:
                with open('./Error_Log.txt','w+') as f:
                    f.write("JSON Conversion Error in "+filename+" for Signals Response: "+str(err))
                continue
            
            # Get existing dataframe for new site, or create an empty dataframe
            current_df = site_dataframes.setdefault(signals_dict["site"], pd.DataFrame())
            
            # Load relevant data into dataframe
            new_dict = signals_dict["signals"]
            new_dict['Time'] = signals_dict["timestamp"]
            new_ser = pd.Series(new_dict)
            new_df = new_ser.to_frame()
            new_df = new_df.transpose()
            new_df.rename(columns = {'SITE_SM_batteryInstPower': 'BatteryPower',
                                     'SITE_SM_siteInstPower': 'SitePower',
                                     'SITE_SM_solarInstPower': 'SolarPower'}, inplace=True)
            
            # If data is missing, record as None
            for key in ['BatteryPower','SitePower','SolarPower','Time']:
                if key not in new_df.columns:
                    new_df[key] = None

            # Update site dataframe with new entry
            if current_df.empty:
                site_dataframes[signals_dict["site"]] = new_df
            else:
                site_dataframes[signals_dict["site"]] = pd.concat([current_df, new_df])

### Process Data

In [3]:
# Gather rows with missing data for later checking
missing_data_df = pd.DataFrame()
for site_id, df in site_dataframes.items():
    missing_data_rows = df[df.isna()]
    missing_data_rows['Site'] = site_id
    missing_data_df = pd.concat([missing_data_df, missing_data_rows])
    
missing_data_df.head()

,BatteryPower,SitePower,SolarPower,Time,Site,SYNC_GridState,SYNC_VL1N_Load,SYNC_VL1N_Main
0,NaN,NaN,NaN,NaN,134a3fa6,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,134a3fa6,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,134a3fa6,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,134a3fa6,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,134a3fa6,NaN,NaN,NaN

In [4]:
# Clean dataframe 
for site_id, df in site_dataframes.items():
    df['BatteryPower'] = df['BatteryPower'].apply(pd.to_numeric)
    df['SitePower'] = df['SitePower'].apply(pd.to_numeric)
    df['SolarPower'] = df['SolarPower'].apply(pd.to_numeric)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

next(iter(site_dataframes.values())).head()

   BatteryPower    SitePower   SolarPower                           Time
0       -2400.0  2379.487860  2426.507517  Wed, 23 Mar 2022 18:54:53 GMT
1       -2426.5  2344.045500  2440.813186  Wed, 23 Mar 2022 18:55:53 GMT
2       -2439.0  2348.230920  2454.669910  Wed, 23 Mar 2022 18:56:54 GMT
3       -2458.0  2360.202930  2456.451990  Wed, 23 Mar 2022 18:57:54 GMT
4       -2460.0  2348.424976  2475.085022  Wed, 23 Mar 2022 18:58:54 GMT

In [5]:
# Save Persistent Dataframe for use in other Notebooks
with open("persistent_dataframe",'wb') as f:
    pickle.dump(site_dataframes, f)